apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcherapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fetcherapp
  template:
    metadata:
      labels:
        app: fetcherapp
    spec:
      containers:
      - name: fetcherapp
        image: acrsdvapplications.azurecr.io/fetcherapp:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx-test
#   template:
#     metadata:
#       labels:
#         app: nginx-test
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:latest
#         ports:
#         - containerPort: 80